### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by culas** [randombenj/arth-steinen-23#1]
Hey @randombenj 

Ich hatte gerade bei uns auf der TV Steinen Webseite den Link zum Wettspiel ergänzt. Habe dann gemerkt, dass der Fliesstext von Arth-Steinen 23 mit der Standard Browserfont angezeigt wird (Open Sans ist definiert aber nicht geladen), sah deinen Namen im Footer und fand das Repo hier. 😁 

Ich bin Web Engineer, falls du etwas Support bei der Weiterentwicklung brauchen kannst, kann ich dich gerne unterstützen.

lg Lucas

**Comment by randombenj** [comment]
Cool danke! 
Würde mich sicher bei dir melden :tada:
